class ValidationError(Exception):
    pass


class CredentialsError(Exception):
    pass